### ISSUE TITLE
System.InvalidOperationException : Test data returned null

### ISSUE THREAD

**Issue by LarsLiden** [andrewlock/blog-examples#59]
I'm trying the JsonFileDataAttribute, but I'm getting the error shown above when it attempts run run "JsonTests" below.  If I put a breakpoint in the constructor for JsonFileDataAttribute I never hit it.  Any ideas?

>         [Theory]
>         [JsonFileData("blah")]
>         public void JsonTests(object test)
>         {
>             Console.WriteLine(JsonConvert.SerializeObject(test));
>         }

**Comment by andrewlock** [comment]
I think that means the json file was empty, or at least no data can be parsed from it.

You probably won't hit the constructor of the attribute due to the way attributes are created by the runtime, but if you put a breakpoint in GetData you may be able to catch the errors 🙂

For reference, I just ran the code in this solution and the tests passed fine: https://github.com/andrewlock/blog-examples/tree/master/XUnitTheoryTests

Good luck!

**Comment by LarsLiden** [comment]
Thanks, Andrew.  It appears to have been something about the way IEnumerable was being instantiated inside my GetData function (which I customized to match my use case).  I changed it and it works now.  Appreciate your response.
