### ISSUE TITLE
Blazor Pre-render / .NET 6 Source Generators

### ISSUE THREAD

**Issue by dotdiego** [andrewlock/blog-examples#77]
Hello,

I've read your series about Blazor with source generators. 
I'm creating a blog using Blazor WASM and markdown files as the backend for my articles.

I want to get all possibles routes (meaning all the paths to get my markdown files). So for now i'm generating a .json with a powershell script as a PostBuildEvent. Then during runtime i'm downloading this file and i can populate my navigation.

But is it possible to embed it in the code directly ?
I would create a service in a .cs that will have that list of paths and returns it. The interface of that service should be added to the DI and injected in my razor files to generate the paths at runtime.

Or is my only option to disable the new source generation of razor ?

**Comment by andrewlock** [comment]
Hi @dotdiego, 

As you saw, the problem with the new razor build style you have is that you _can't_ use a source generator to easily get the components. The way I see it, you have several options:

* Carry on with what you're doing
* Rework the build process slightly:
  * Build your app
  * Run the PostBuildEvent
  * Rebuild your app and embed the json as an embedded source. This way it ships down in the same dlls
* Do the same as above, but convert your powershell script to output a .cs file instead of json, and just compile as normal
* Disable the Blazor source generations, and do the other approach you describe
* Keep the Blazor source generation, Parse the .razor files yourself, and take the approach you describe

As for which approach you want to take, that's entirely dependent on how much pain you want 😄 If it was me, I would _probably_ carry on with the approach you're already using, until they fix the source gen issue in .NET 7🤞 Given the size of Blazor Wasm, what's one more JSON file between friends 😉

**Comment by dotdiego** [comment]
Haha thanks for the quick reply.
I do not understand exactly everything about source generators yet, but yes I think i'll keep the pain level to a minimum seeing the other options i have for now. And that i just need a year to wait if they fix this issue in .NET 7
